# Generated by Django 4.2.3 on 2023-07-14 17:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "img",
                    models.ImageField(
                        default="static/img/App/ProductImg/default.png",
                        upload_to="static/img/App/ProductImg/",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("costPrice", models.IntegerField()),
                ("mrp", models.IntegerField()),
                ("sellingPrice", models.IntegerField()),
                ("qty", models.IntegerField()),
                ("tax", models.IntegerField()),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Product.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
